"""asignee id not nullable

Revision ID: 00b4dbe412cf
Revises: c9ef0c33ae48
Create Date: 2023-09-29 09:18:24.955369

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00b4dbe412cf"
down_revision: Union[str, None] = "c9ef0c33ae48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "asignee_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "asignee_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
