"""make task status column required

Revision ID: 5acacb36ba84
Revises: 296ad53451eb
Create Date: 2023-09-27 10:24:42.806039

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5acacb36ba84"
down_revision: Union[str, None] = "296ad53451eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("taskhistory", "status", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("taskhistory", "status", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
