"""add blocking tasks

Revision ID: 6ec9b464969e
Revises: 00b4dbe412cf
Create Date: 2023-09-29 09:20:50.873557

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ec9b464969e"
down_revision: Union[str, None] = "00b4dbe412cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "taskblocking",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("blocking_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["blocking_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("taskblocking")
    # ### end Alembic commands ###
