"""set up relationship for cascade delete

Revision ID: bc41a8448fea
Revises: 5acacb36ba84
Create Date: 2023-09-27 11:17:22.170172

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc41a8448fea"
down_revision: Union[str, None] = "5acacb36ba84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("taskhistory_task_id_fkey", "taskhistory", type_="foreignkey")
    op.create_foreign_key(
        None, "taskhistory", "tasks", ["task_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "taskhistory", type_="foreignkey")
    op.create_foreign_key(
        "taskhistory_task_id_fkey", "taskhistory", "tasks", ["task_id"], ["id"]
    )
    # ### end Alembic commands ###
