version: '3'
services:
  waveaccess-python-assignment:
    container_name: waveaccess-python-assignment
    command: uvicorn main:app --reload --host 0.0.0.0 --port ${FASTAPI_PORT}
    build: app/
    volumes: 
      - ./app/src/:/code
    restart: always
    depends_on:
      - pgsql
    env_file:
      - .env
    ports:
      - ${FASTAPI_PORT}:${FASTAPI_PORT}
    networks:
      - backend
  
  pgsql:
    container_name: pgsql
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    user: ${POSTGRES_USER}
    ports:
      - ${PGPORT}:${PGPORT}
    expose:
      - ${PGPORT}
    networks:
      - backend

volumes:
  waveaccess-python-assignment:
  postgres_data:

networks:
  backend:
    driver: bridge